application:
  name: laboratorio-deploy

server:
  user: juniorwinkler

environments:
  test:
    name: TEST
    path: /var/www/deploy-lab-test
    port: 5001
    service: deploy-lab-test.service

  prod:
    name: PROD
    path: /var/www/deploy-lab-prod
    port: 5002
    service: deploy-lab-prod.service
